# Prerequisites: pom.xml and appropriate project structure should exist in the repository.

image: markhobson/maven-chrome:jdk-8


pipelines:
  default:
        - step:
            name: Build and Test
            caches:
              - maven
            script:
              - mvn -B clean test -Dgroups=@SmokeTest --file pom.xml


            after-script:
              # Collect checkstyle results, if any, and convert to Bitbucket Code Insights.
              - pipe: atlassian/checkstyle-report:0.3.0

            artifacts:
               - target/surefire-reports/emailable-report.html