BaseURL_Teachers = https://teach-api.brightchamps.com/v1
Token_P = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwaG9uZU51bWJlciI6Ijg0MzM5MTg0MjMiLCJpYXQiOjE2NDgwMzQ2NjIsImV4cCI6MTY3OTEzODY2Mn0.rm4IxKU3aCt3iWkjHMFr2hNHcSX7vnqP7o9CXzFd75w
APIResponseTime = 10000
phoneNumber = 8130865152
studentId = 51540
Demo_studentID = 2247360
Token_DemoUser = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwaG9uZU51bWJlciI6IjUzMTAwMDAwMDMiLCJpYXQiOjE2NDgxMTY4ODksImV4cCI6MTY3OTIyMDg4OX0.CQb60vGaRWhUWRtigJyjoUY9x4PqtajkuWAYFUbBETA
Email = apurva.kushwaha@mailinator.com
Password = qwerty



###############################################################################################################################################################################
#MySql Queries

Fetch_OTP = Select otp from brightchamps.otp_validator where user = 'apurva.kushwaha@mailinator.com'
Get_ResetToken = Select reset_password_token from brightchamps.paid_students where email = 'apurva.kushwaha@mailinator.com'
DeleteGlobalHouseEntry = DELETE FROM `brightchamps`.`scheduled_global_house_classes` WHERE (`user_id` = '51540');